// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/olegtrautvein/testcrd/operatorsdk/kublr-operator/pkg/apis/features/v1alpha1.Logging":       schema_pkg_apis_features_v1alpha1_Logging(ref),
		"github.com/olegtrautvein/testcrd/operatorsdk/kublr-operator/pkg/apis/features/v1alpha1.LoggingSpec":   schema_pkg_apis_features_v1alpha1_LoggingSpec(ref),
		"github.com/olegtrautvein/testcrd/operatorsdk/kublr-operator/pkg/apis/features/v1alpha1.LoggingStatus": schema_pkg_apis_features_v1alpha1_LoggingStatus(ref),
	}
}

func schema_pkg_apis_features_v1alpha1_Logging(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Logging is the Schema for the loggings API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/olegtrautvein/testcrd/operatorsdk/kublr-operator/pkg/apis/features/v1alpha1.LoggingSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/olegtrautvein/testcrd/operatorsdk/kublr-operator/pkg/apis/features/v1alpha1.LoggingStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/olegtrautvein/testcrd/operatorsdk/kublr-operator/pkg/apis/features/v1alpha1.LoggingSpec", "github.com/olegtrautvein/testcrd/operatorsdk/kublr-operator/pkg/apis/features/v1alpha1.LoggingStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_features_v1alpha1_LoggingSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "LoggingSpec defines the desired state of Logging",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_features_v1alpha1_LoggingStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "LoggingStatus defines the observed state of Logging",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
